### ISSUE TITLE
Alias for !important

### ISSUE THREAD

**Issue by tenhobi** [HoBi/postcss-czech-stylesheets#2]
Add more gentle alias for `!important`. _(Current translete is `!kurva`.)_
- [ ] `!dulezite`

**Comment by janmarek** [comment]
We should have plenty of aliases for !important. Let users express their current feelings!

**Comment by tenhobi** [comment]
I dont think so this is a good idea. We should make some solid structure which may be extended by users options (#6).

Our aliases for !important will be the `!kurva` and the gentle `!dulezite`.

**Comment by tenhobi** [comment]
`!funguj` can be also cool :smile_cat:

**Comment by tenhobi** [comment]
Will add tomorrow for !dulezite.
