### ISSUE TITLE
Bug when a value in decl is used multiple times

### ISSUE THREAD

**Issue by tenhobi** [HoBi/postcss-czech-stylesheets#4]
Even through I added `replaceAll()` ([there](https://github.com/HoBi/postcss-czech-stylesheets/blob/master/src/index.js#L8-L11)) function it should not replace all occurrences, but in normal JS tested in JSFiddle or so it does.

``` css
barva-rámečku: #aaa průhledný průhledný průhledný;
```

Only the first one is replaced.

``` css
border-color: #aaa transparent průhledný průhledný;
```

**Comment by HoBi** [comment]
Take a look at https://github.com/postcss/postcss/blob/master/docs/api.md#declaration-node

**Comment by tenhobi** [comment]
No idea how to solve this...
